program elphy2_DX9;



uses
  Forms,
  mdac in 'mdac.pas',
  EditScroll1 in 'EditScroll1.pas' {EditScroll: TFrame},
  ColorFrame1 in 'ColorFrame1.pas' {ColFrame: TFrame},
  DisplayUOFrame1 in 'DisplayUOFrame1.pas' {UODisplay: TFrame},
  DisplayFrame1 in 'DisplayFrame1.pas' {DispFrame: TFrame},
  TPform0 in 'TPform0.pas' {Pform},
  FrameTable1 in 'FrameTable1.pas' {TableFrame: TFrame},
  FuncProp in 'FuncProp.pas' {FunctionProp},
  Getdeg0 in 'Getdeg0.pas' {Degform},
  Defform in 'defForm.pas' {GenForm},
  stimForm in 'stimForm.pas' {stimulusForm},
  Multg0 in 'multg0.pas' {MultiGform},
  Dtbedit1 in 'DtbEdit1.pas' {ArrayEditor},
  Detform1 in 'Detform1.pas' {DetPanel},
  colorPan1 in 'colorPan1.pas' {colorPan: TFrame},
  DUlex5 in 'DUlex5.pas',
  cyberKsimBrd1 in 'cyberKsimBrd1.pas',
  MemManager1 in 'MemManager1.pas',
  DD1322brd in 'DD1322brd.pas',
  DBtable1 in 'DBtable1.pas',
  stmNI in 'stmNI.pas',
  TextFile1 in 'TextFile1.pas',
  regEditOptions in 'regEditOptions.pas' {RegOptions},
  DateForm1 in 'DateForm1.pas' {GetDateForm},
  FrameDate1 in 'FrameDate1.pas' {Frame1: TFrame},
  PCL0 in 'PCL0.pas',
  GLprintDlg in 'GLprintDlg.pas' {GlprintForm},
  VSSyncPrm in 'VSSyncPrm.pas' {GetVSsyncParam},
  ErrorForm1 in 'ErrorForm1.pas' {ErrorForm},
  stmBMcorrection1 in 'stmBMcorrection1.pas' {BMcorrection},
  CreateAVI1 in 'CreateAVI1.pas' {CreateAVIform},
  SerialCom1 in 'SerialCom1.pas',
  QueryString1 in 'QueryString1.pas' {QueryString},
  SyslistTreeView in 'SyslistTreeView.pas' {SyslistView: TFrame},
  stmStreamer1 in 'stmStreamer1.pas',
  SimRTneuronBrd in 'SimRTneuronBrd.pas',
  CpList0 in 'CpList0.pas',
  OIseqProp1 in 'OIseqProp1.pas' {OIseqProp},
  Darbre1 in 'Darbre1.pas',
  SpkBlock1 in 'SpkBlock1.pas',
  Kernels in 'Kernels.pas',
  DNkernel1 in 'DNkernel1.pas',
  stmTexFile in 'stmTexFile.pas',
  MathSpeedTest in 'MathSpeedTest.pas',
  DXgrid1 in 'DXgrid1.pas',
  stmOptPsth1 in 'stmOptPsth1.pas',
  KStest1 in 'KStest1.pas',
  ReducStim1 in 'ReducStim1.pas',
  randTest2 in 'randTest2.pas',
  stmOdat2 in 'stmOdat2.pas',
  SearchPath1 in 'SearchPath1.pas' {GetSearchPath},
  laguerre1 in 'laguerre1.pas',
  D3DX9G in 'D3DX9G.pas',
  Direct3D9G in 'Direct3D9G.pas',
  LCR1 in 'LCR1.pas',
  LCR_api in 'LCR_api.pas',
  stmMatlabMat in 'stmMatlabMat.pas',
  RestClientTest in 'RestClientTest.pas' {RestForm},
  stmRestObject in 'stmRestObject.pas',
  stmMotionCloud3 in 'stmMotionCloud3.pas',
  CyberK4 in 'CyberK4.pas',
  cyberKbrd2 in 'cyberKbrd2.pas',
  cyberKOptions in 'cyberKOptions.pas' {CyberKOpt},
  stmObjList1 in 'stmObjList1.pas',
  NewMglist1 in 'NewMglist1.pas' {NewMGlist},
  BLBtransform1 in 'BLBtransform1.pas',
  DescLabchart1 in 'DescLabchart1.pas',
  Chris1 in 'Chris1.pas',
  hdf5dll in 'hdf5dll.pas',
  hdf5_lite in 'hdf5_lite.pas',
  IIR1 in 'IIR1.pas',
  ipp17ex in 'ipp17ex.pas',
  ippvm17 in 'ippvm17.pas';

{$R *.RES}

begin
  Application.Initialize;
  Application.CreateForm(TMainDac, MainDac);
  Application.Run;
end.

