  gsIdVersionMajor = 10;
  {$NODEFINE gsIdVersionMajor}
  gsIdVersionMinor = 6;
  {$NODEFINE gsIdVersionMinor}
  gsIdVersionRelease = 1;
  {$NODEFINE gsIdVersionRelease}
  gsIdVersionBuild = 5183;
  {$NODEFINE gsIdVersionBuild}

  (*$HPPEMIT '#define gsIdVersionMajor 10'*)
  (*$HPPEMIT '#define gsIdVersionMinor 6'*)
  (*$HPPEMIT '#define gsIdVersionRelease 1'*)
  (*$HPPEMIT '#define gsIdVersionBuild 5183'*)
  (*$HPPEMIT ''*)

  gsIdVersion = '10.6.1.5183'; {do not localize}
  gsIdProductName = 'Indy';  {do not localize}
